workflows:
  android-workflow:
    name: Tajgram VIP Factory Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: "17"
    scripts:
      - name: Set up Java Development Kit
        script: |
          jdk switch 17
          echo "✅ Java 17 фаъол шуд!"

      - name: Recreate Factory Keystore Inside Config
        script: |
          mkdir -p TMessagesProj/config/
          rm -f TMessagesProj/config/release.keystore || true
          
          # Сабти автоматӣ ба Properties
          cat <<EOF > TMessagesProj/config/keystore.properties
          keyAlias=$RELEASE_KEY_ALIAS
          keyPassword=$RELEASE_KEY_PASSWORD
          storePassword=$RELEASE_STORE_PASSWORD
          EOF
          
          # Сохтани калид мустақим аз рӯи номи калиди шумо бе кавычка
          keytool -genkeypair -v -keystore TMessagesProj/config/release.keystore \
            -alias $RELEASE_KEY_ALIAS \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass $RELEASE_STORE_PASSWORD \
            -keypass $RELEASE_KEY_PASSWORD \
            -dname "CN=Tajgram, OU=VIP, O=Messenger, L=Dushanbe, S=Tajikistan, C=TJ"
          
          # ЧОП КАРДАНИ SHA-1 ВА SHA-256 ДАР ЛОГҲОИ CODEMAGIC
          echo "=== САНҶИШИ ПАСПОРТИ РАҚАМИИ БАРНОМА ==="
          keytool -list -v -keystore TMessagesProj/config/release.keystore -storepass $RELEASE_STORE_PASSWORD | grep -E "SHA1:|SHA256:" || true
          echo "========================================="
          
          echo "✅ Калид бо номи tajgram_key бехато сохта шуд!"

      - name: Build Tajgram VIP Release APK Without Tests
        script: |
          chmod +x gradlew
          ./gradlew :TMessagesProj_App:assembleRelease -x test --generateLabels --no-daemon

    artifacts:
      - TMessagesProj_App/build/outputs/apk/release/*.apk
