workflows:
  android-workflow:
    name: Tajgram VIP Factory Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: "17"
    scripts:
      - name: Set up Java Development Kit
        script: |
          jdk switch 17
          echo "✅ Java 17 фаъол шуд!"

      - name: Recreate Factory Keystore Inside Config
        script: |
          mkdir -p TMessagesProj/config/
          rm -f TMessagesProj/config/release.keystore || true
          
          # Ин ҷо мо файлро аз тариқи тағирёбандаҳои махфии шумо месозем
          cat <<EOF > TMessagesProj/config/keystore.properties
          keyAlias=$RELEASE_KEY_ALIAS
          keyPassword=$RELEASE_KEY_PASSWORD
          storePassword=$RELEASE_STORE_PASSWORD
          EOF
          
          # ИЛОВАИ БЕХАТАР: Чоп кардани SHA-1 ва SHA-256 дар логҳои Codemagic
          keytool -list -v -keystore TMessagesProj/config/release.keystore -storepass "$RELEASE_STORE_PASSWORD" | grep -E "SHA1:|SHA256:" || true
          
          echo "✅ Калидҳои махфӣ аз Android Sign бомуваффақият пайваст шуданд!"

      - name: Build Tajgram VIP Release APK Without Tests
        script: |
          chmod +x gradlew
          ./gradlew :TMessagesProj_App:assembleRelease -x test --generateLabels --no-daemon

    artifacts:
      - TMessagesProj_App/build/outputs/apk/release/*.apk
