workflows:
  android-workflow:
    name: Tajgram VIP Factory Build
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      vars:
        JAVA_VERSION: "17"
    scripts:
      - name: Set up Java Development Kit
        script: |
          jdk switch 17
          echo "✅ Java 17 фаъол шуд!"
      - name: Recreate Factory Keystore Inside Config
        script: |
          # РОБОТ ХУДАШ КАЛИДИ РАСМИИ ИМЗОРО РОСТ ДАР ПАПКAИ CONFIG МEСOЗAД
          mkdir -p TMessagesProj/config/
          rm -f TMessagesProj/config/release.keystore || true
          
          keytool -genkey -v -keystore TMessagesProj/config/release.keystore \
            -alias AndroidDebugKey -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass android -keypass android -dname "CN=Tajgram, OU=VIP, O=Messenger, L=Dushanbe, S=Tajikistan, C=TJ"
          
          cat <<EOF > TMessagesProj/config/keystore.properties
          keyAlias=AndroidDebugKey
          keyPassword=android
          storePassword=android
          EOF
          echo "✅ Калиди ҳақиқии имзо дар папкаи config 100% маҳкам шуд!"
      - name: Build Tajgram VIP Release APK Without Tests
        script: |
          chmod +x gradlew
          # ИҶРОИ ФАРМОНИ ҲАҚИҚИИ РEЛИЗ БO КАЛИДИ ЗАВOДӢ
          ./gradlew assembleRelease -x test -x generateScheme --no-daemon
    artifacts:
      - TMessagesProj/build/outputs/apk/release/*.apk
      - "**/build/outputs/apk/**/*.apk"
