name: 🎨 AUTOMATIC MAIN REPO ICON OVERWRITER

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  overwrite_logos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Code Fresh
        uses: actions/checkout@v4

      - name: Purge Only Duplicate Webp Icons Safely
        run: |
          git config --global user.name "Saidjun Chief Developer"
          git config --global user.email "saidjun@tajgram.messenger"
          
          # РОБОТ ТАНҲО ФАҚАТ ҲАМИН ФАЙЛҲОИ ТАҚРОРИРО АЗ РЕШАШ ТOЗA МEКУНAД!
          git rm -f TMessagesProj/src/main/res/drawable-mdpi/notification.webp || true
          git rm -f TMessagesProj/src/main/res/drawable-mdpi/status_icon.webp || true
          
          git rm -f TMessagesProj/src/main/res/drawable-hdpi/notification.webp || true
          git rm -f TMessagesProj/src/main/res/drawable-hdpi/status_icon.webp || true
          
          git rm -f TMessagesProj/src/main/res/drawable-xhdpi/notification.webp || true
          git rm -f TMessagesProj/src/main/res/drawable-xhdpi/status_icon.webp || true
          
          git rm -f TMessagesProj/src/main/res/drawable-xxhdpi/notification.webp || true
          git rm -f TMessagesProj/src/main/res/drawable-xxhdpi/status_icon.webp || true
          
          git rm -f TMessagesProj/src/main/res/drawable-xxxhdpi/notification.webp || true
          git rm -f TMessagesProj/src/main/res/drawable-xxxhdpi/status_icon.webp || true
          
          # Сабти автоматӣ ба лоиҳа
          git commit -m "🎨 FIX: Only duplicate webp notification icons purged successfully!" || exit 0
          git push origin HEAD:${{ github.ref_name }} --force
