name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4
      with:
        clean: true

    # Танзими Java 17 барои он ки GitHub Actions хато надиҳад
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # Насби автоматии Android SDK ва асбобҳои C++ (CMake, NDK)
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    # ФАРМОНИ ҲАҚИҚӢ: Пайваст кардани калидҳо аз Secrets барои сохтани версияи аслӣ
    - name: Build with Gradle Factory Command
      env:
        RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
        RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        RELEASE_STORE_PASSWORD: ${{ secrets.RELEASE_STORE_PASSWORD }}
      run: |
        chmod +x gradlew
        ./gradlew :TMessagesProj_App:assembleRelease --stacktrace

    # Боркунии APK-и ҳақиқӣ (Аз папкаи release)
    - name: Upload Finished APK Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Tajgram-Official-APK
        path: TMessagesProj_App/build/outputs/apk/release/*.apk
