name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4
      with:
        clean: true

    # Танзими Java 17 барои он ки GitHub Actions хато надиҳад
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # Насби автоматии Android SDK ва асбобҳои C++ (CMake, NDK)
    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    # Фармони дақиқ барои ҷамъоварии модули асосии Tajgram
    - name: Build with Gradle Factory Command
      run: |
        chmod +x gradlew
        ./gradlew :TMessagesProj_App:assembleDebug --stacktrace

    # Боркунии барномаи тайёр пас аз сохтан
    - name: Upload Finished APK Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Factory-Telegram-APK
        path: TMessagesProj_App/build/outputs/apk/debug/*.apk
