name: Key Factory Only

on:
  workflow_dispatch:

jobs:
  create_key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4
      with:
        clean: true
        # Муҳим барои иҷозати сабти файл дар папка
        token: ${{ secrets.GITHUB_TOKEN }}

    # 1. СОХТАНИ КАЛИД МАҲЗ ДАР ДОХИЛИ ПАПКАИ CONFIG
    - name: Generate Keystore Directly Inside Config Folder
      run: |
        mkdir -p TMessagesProj/config/
        rm -f TMessagesProj/config/release.keystore || true
        keytool -genkeypair -v -keystore TMessagesProj/config/release.keystore \
          -alias "${{ secrets.RELEASE_KEY_ALIAS }}" \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -storepass "${{ secrets.RELEASE_STORE_PASSWORD }}" \
          -keypass "${{ secrets.RELEASE_KEY_PASSWORD }}" \
          -dname "CN=Tajgram, OU=VIP, O=Messenger, L=Dushanbe, S=Tajikistan, C=TJ"

    # 2. СИРРИ АСЛӢ: Худи сервер файлро ба папкаи GitHub-и ту бор ва сабт мекунад!
    - name: Commit and Push Keystore File Back to Repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        git add TMessagesProj/config/release.keystore
        git commit -m "Автоматӣ: Сабт ва доимӣ кардани калиди шахсии Tajgram" || echo "Файл аллакай сабт шудааст"
        git push origin HEAD:${{ github.ref }} || echo "Хатои боркунӣ"

    # 3. НАМОИШИ АНИҚИ SHA БАРОИ СКРИНШОТ
    - name: Check SHA Fingerprints with Eyes
      run: |
        echo "=== САНҶИШИ ПАСПОРТИ РАҚАМИИ БАРНОМА ==="
        keytool -list -v -keystore TMessagesProj/config/release.keystore \
          -storepass "${{ secrets.RELEASE_STORE_PASSWORD }}" | grep -E "SHA1:|SHA256:"
        echo "========================================="

    # 4. СКАЧАТ КАРДАНИ ХУДИ ФАЙЛ БА ТЕЛЕФОН
    - name: Upload Keystore File For Download
      uses: actions/upload-artifact@v4
      with:
        name: My-Permanent-Keystore-File
        path: TMessagesProj/config/release.keystore
