name: Key Factory Only

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4
      with:
        clean: true
        token: ${{ secrets.GITHUB_TOKEN }}

    # 1. СОХТАНИ КАЛИД МАҲЗ ДАР ҶОИ КАЛИДИ ЗАВОДИИ ДУРОВ (ПАПКАИ CONFIG)
    - name: Generate Keystore Directly Inside Config Folder
      run: |
        mkdir -p TMessagesProj/config/
        rm -f TMessagesProj/config/release.keystore || true
        keytool -genkeypair -v -keystore TMessagesProj/config/release.keystore \
          -alias "${{ secrets.RELEASE_KEY_ALIAS }}" \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -storepass "${{ secrets.RELEASE_STORE_PASSWORD }}" \
          -keypass "${{ secrets.RELEASE_KEY_PASSWORD }}" \
          -dname "CN=Tajgram, OU=VIP, O=Messenger, L=Dushanbe, S=Tajikistan, C=TJ"

    # 2. БОР КАРДАН ВА САБТ КАРДАНИ ФАЙЛ БО АЛОМАТИ ОТАШ 🔥 ДАР ПАПКАИ CONFIG
    - name: Commit and Push Keystore File Back to Repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        git add TMessagesProj/config/release.keystore
        git commit -m "🔥 TAJGRAM ULTIMATE OVERHAUL: Сабти калиди якумра ба папкаи Config" || echo "Файл аллакай ҳаст"
        git push origin HEAD:${{ github.ref }} --force

    # 3. НАМОИШИ АНИҚИ SHA БАРОИ СКРИНШОТ ВА ФАЙРБЕЙС
    - name: Check SHA Fingerprints with Eyes
      run: |
        echo "=== САНҶИШИ ПАСПОРТИ РАҚАМИИ БАРНОМА ==="
        keytool -list -v -keystore TMessagesProj/config/release.keystore \
          -storepass "${{ secrets.RELEASE_STORE_PASSWORD }}" | grep -E "SHA1:|SHA256:"
        echo "========================================="
