name: Key Factory Only

on:
  workflow_dispatch:

jobs:
  create_key:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4
      with:
        clean: true

    # СОХТАНИ КАЛИД МАҲЗ БА ҶОИ КАЛИДИ ДУРОВ ДАР ДОХИЛИ ПАПКАИ CONFIG
    - name: Generate Keystore Directly Inside Config Folder
      run: |
        mkdir -p TMessagesProj/config/
        rm -f TMessagesProj/config/release.keystore || true
        keytool -genkeypair -v -keystore TMessagesProj/config/release.keystore \
          -alias "${{ secrets.RELEASE_KEY_ALIAS }}" \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -storepass "${{ secrets.RELEASE_STORE_PASSWORD }}" \
          -keypass "${{ secrets.RELEASE_KEY_PASSWORD }}" \
          -dname "CN=Tajgram, OU=VIP, O=Messenger, L=Dushanbe, S=Tajikistan, C=TJ"

    # НАМОИШИ АНИҚИ SHA-1 ВА SHA-256 БАРОИ СКРИНШОТ ВА ФАЙРБЕЙС
    - name: Check SHA Fingerprints with Eyes
      run: |
        echo "=== САНҶИШИ ПАСПОРТИ РАҚАМИИ БАРНОМА ==="
        keytool -list -v -keystore TMessagesProj/config/release.keystore \
          -storepass "${{ secrets.RELEASE_STORE_PASSWORD }}" | grep -E "SHA1:|SHA256:"
        echo "========================================="

    # СКАЧАТ КАРДАНИ ХУДИ ФАЙЛ МУСТАҚИМ АЗ ПАПКАИ CONFIG БА ТЕЛЕФОН
    - name: Upload Keystore File For Download
      uses: actions/upload-artifact@v4
      with:
        name: My-Permanent-Keystore-File
        path: TMessagesProj/config/release.keystore
