name: Inject Smart Proxy Code
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  inject:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Add Smart Proxy Configuration
        run: |
          find . -type f -name "BuildVars.java" -exec sed -i '/public static boolean DEBUG_VERSION/a \    public static String PROXY_ADDRESS = "172.67.182.203";\n    public static int PROXY_PORT = 443;\n    public static String PROXY_SECRET = "ee00000000000000000000000000000000636c6f7564666c6172652e636f6d";' {} +
      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Inject built-in anti-block proxy for Moscow"
          git push origin HEAD:${{ github.ref }}
