name: 2-Second Reset Only buildSrc To Original Factory State

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  reset_src:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Code Fresh
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Overwrite ONLY buildSrc Folder From Durov
        run: |
          git config --global user.name "Saidjun Chief Developer"
          git config --global user.email "saidjun@tajgram.messenger"
          
          # 1. ТАНҲО ТОЗА КАРДАНИ ҲАМИН ЯК ПАПКАИ ВАЙРОНШУДА
          rm -rf buildSrc
          
          # 2. НУСХАБАРДОРИИ ТАНҲО ҲАМИН ЯК ПАПКА АЗ РЕПОЗИТОРИЯИ ДУРОВ
          git clone --depth=1 https://github.com/DrKLO/Telegram.git durov_temp
          cp -r durov_temp/buildSrc ./
          rm -rf durov_temp
          
          # 3. САБТИ ОН ДАР СAЙТ
          git add buildSrc/
          git commit -m "⚙️ SYSTEM: Only buildSrc folder restored to factory defaults!" || exit 0
          git push origin HEAD:${{ github.ref_name }} --force
